channels:
- currentCSV: redhat-marketplace-operator.v0.2.0
  name: beta
- currentCSV: redhat-marketplace-operator.v0.2.0
  name: stable
defaultChannel: stable
packageName: redhat-marketplace-operator
