apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: rhm-metric-state-tls
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: rhm-metric-state
  name: rhm-metric-state-service
spec:
  ports:
    - name: web
      port: 8080
      targetPort: web
    - name: metrics
      port: 8081
      targetPort: metrics
    - name: https
      port: 9092
      targetPort: https
    - name: https-metrics
      port: 9093
      targetPort: https-metrics
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: rhm-metric-state
  sessionAffinity: ClientIP
  type: ClusterIP
