dist: focal

language: go

services:
  - docker

before_script:
  - go get github.com/onsi/ginkgo/ginkgo
  - docker pull docker.io/docker/dockerfile:experimental
  - docker pull docker.io/docker/dockerfile-copy:v0.1.9
  - VERSION=`go run scripts/version/main.go`

go:
  - "1.15.x"

env:
  global:
    - IMAGE_REGISTRY=quay.io/rh-marketplace DOCKER_CLI_EXPERIMENTAL=enabled DOCKER_BUILDKIT=1 QUAY_EXPIRATION=never
  
jobs:
  include:
    # Building ppc64le container images and pushing to quay.io
    - arch: ppc64le
      script:
      - docker --version
      - if [ "x$VERSION" = "x" ]; then VERSION=${TRAVIS_COMMIT}; fi
      - echo  ${VERSION}
      - echo "Login to Quay.io docker account..."
      - docker login -u="${ROBOT_USER_NAME}" -p="${ROBOT_PASS_PHRASE}" quay.io
      - echo "Building the Red Hat Marketplace operator images for ppc64l..."
      - >
        docker build -t "quay.io/rh-marketplace/golang-base:1.15" 
        --build-arg ARCH=ppc64le 
        --build-arg name="Operator"
        --build-arg exec=./cmd/manager
        --build-arg bin=redhat-marketplace-operator
        --build-arg app_version=\"${VERSION}\"
        --build-arg quay_expiration=\"${QUAY_EXPIRATION}\" 
        -f build/base.Dockerfile .
      - > 
        docker build -t "quay.io/aosadchyy/redhat-marketplace-operator:${VERSION}-ppc64le" 
        --build-arg ARCH=ppc64le 
        --build-arg name="Operator"
        --build-arg exec=./cmd/manager
        --build-arg bin=redhat-marketplace-operator
        --build-arg app_version=\"${VERSION}\"
        --build-arg quay_expiration=\"${QUAY_EXPIRATION}\" 
        -f build/Dockerfile .
      - >
        docker build -t "quay.io/aosadchyy/redhat-marketplace-metric-state:${VERSION}-ppc64le" 
        --build-arg ARCH=ppc64le 
        --build-arg name="Operator"
        --build-arg exec=./cmd/manager
        --build-arg bin=redhat-marketplace-operator
        --build-arg app_version=\"${VERSION}\"
        --build-arg quay_expiration=\"${QUAY_EXPIRATION}\" 
        -f build/metricState.Dockerfile .
      - >
        docker build -t "quay.io/aosadchyy/redhat-marketplace-reporter:${VERSION}-ppc64le" 
        --build-arg ARCH=ppc64le 
        --build-arg name="Operator"
        --build-arg exec=./cmd/manager
        --build-arg bin=redhat-marketplace-operator
        --build-arg app_version=\"${VERSION}\"
        --build-arg quay_expiration=\"${QUAY_EXPIRATION}\" 
        -f build/reporter.Dockerfile .
      - >
        docker build -t "quay.io/aosadchyy/redhat-marketplace-authcheck:${VERSION}-ppc64le" 
        --build-arg ARCH=ppc64le 
        --build-arg name="Operator"
        --build-arg exec=./cmd/manager
        --build-arg bin=redhat-marketplace-operator
        --build-arg app_version=\"${VERSION}\"
        --build-arg quay_expiration=\"${QUAY_EXPIRATION}\" 
        -f build/authcheck.Dockerfile .
      - echo "Pushing images ..."
      - docker push "quay.io/kandarpamalipeddi/redhat-marketplace-operator:${VERSION}-ppc64le"
      - docker push "quay.io/kandarpamalipeddi/redhat-marketplace-metric-state:${VERSION}-ppc64le"
      - docker push "quay.io/kandarpamalipeddi/redhat-marketplace-reporter:${VERSION}-ppc64le"
      - docker push "quay.io/kandarpamalipeddi/redhat-marketplace-authcheck:${VERSION}-ppc64le"
      - echo "Docker Image push to quay.io is done !"
      - make test-ci-unit
    
    # Building s390x container images and pushing to quay.io
    - arch: s390x
      script:
      - docker --version
      - if [ "x$VERSION" = "x" ]; then VERSION=${TRAVIS_COMMIT}; fi
      - echo  ${VERSION}
      - echo "Login to Quay.io docker account..."
      - docker login -u="${ROBOT_USER_NAME_S390X}" -p="${ROBOT_PASS_PHRASE_S390X}" quay.io
      - echo "Building the Red Hat Marketplace operator images for s390x..."
      - >
        docker build -t "quay.io/rh-marketplace/golang-base:1.15" 
        --build-arg ARCH=s390x 
        --build-arg name="Operator"
        --build-arg exec=./cmd/manager
        --build-arg bin=redhat-marketplace-operator
        --build-arg app_version=\"${VERSION}\"
        --build-arg quay_expiration=\"${QUAY_EXPIRATION}\" 
        -f build/base.Dockerfile .
      - > 
        docker build -t "quay.io/aosadchyy/redhat-marketplace-operator:${VERSION}-s390x" 
        --build-arg ARCH=s390x 
        --build-arg name="Operator"
        --build-arg exec=./cmd/manager
        --build-arg bin=redhat-marketplace-operator
        --build-arg app_version=\"${VERSION}\"
        --build-arg quay_expiration=\"${QUAY_EXPIRATION}\" 
        -f build/Dockerfile .
      - >
        docker build -t "quay.io/aosadchyy/redhat-marketplace-metric-state:${VERSION}-s390x" 
        --build-arg ARCH=s390x 
        --build-arg name="Operator"
        --build-arg exec=./cmd/manager
        --build-arg bin=redhat-marketplace-operator
        --build-arg app_version=\"${VERSION}\"
        --build-arg quay_expiration=\"${QUAY_EXPIRATION}\" 
        -f build/metricState.Dockerfile .
      - >
        docker build -t "quay.io/aosadchyy/redhat-marketplace-reporter:${VERSION}-s390x" 
        --build-arg ARCH=s390x 
        --build-arg name="Operator"
        --build-arg exec=./cmd/manager
        --build-arg bin=redhat-marketplace-operator
        --build-arg app_version=\"${VERSION}\"
        --build-arg quay_expiration=\"${QUAY_EXPIRATION}\" 
        -f build/reporter.Dockerfile .
      - >
        docker build -t "quay.io/aosadchyy/redhat-marketplace-authcheck:${VERSION}-s390x" 
        --build-arg ARCH=s390x 
        --build-arg name="Operator"
        --build-arg exec=./cmd/manager
        --build-arg bin=redhat-marketplace-operator
        --build-arg app_version=\"${VERSION}\"
        --build-arg quay_expiration=\"${QUAY_EXPIRATION}\" 
        -f build/authcheck.Dockerfile .
      - echo "Pushing images ..."
      - docker push "quay.io/aosadchyy/redhat-marketplace-operator:${VERSION}-s390x"
      - docker push "quay.io/aosadchyy/redhat-marketplace-metric-state:${VERSION}-s390x"
      - docker push "quay.io/aosadchyy/redhat-marketplace-reporter:${VERSION}-s390x"
      - docker push "quay.io/aosadchyy/redhat-marketplace-authcheck:${VERSION}-s390x"
      - echo "Docker Image push to quay.io is done !"
      - make test-ci-unit-no-race
    
