apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: redhat-marketplace-operator
build:
  local:
    concurrency: 0
    useBuildkit: true
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}'
  artifacts:
    - image: redhat-marketplace-operator
      docker:
        dockerfile: build/Dockerfile
        buildArgs:
          VERSION: '{{.VERSION}}'
        cacheFrom:
          - registry.access.redhat.com/ubi8/ubi:latest
          - quay.io/rh-marketplace/golang-base:1.14
    - image: redhat-marketplace-reporter
      docker:
        dockerfile: build/reporter.Dockerfile
        buildArgs:
          VERSION: '{{.VERSION}}'
        cacheFrom:
          - registry.access.redhat.com/ubi8/ubi:latest
          - quay.io/rh-marketplace/golang-base:1.14
deploy:
  helm:
    releases:
      - name: rhm-operator
        artifactOverrides:
          image: redhat-marketplace-operator
          reporterImage: redhat-marketplace-reporter
        chartPath: deploy/chart
        valuesFiles:
          - deploy/chart/values.yaml
  kubectl:
    manifests:
      - deploy/crds/*cr.yaml
    flags:
      disableValidation: true
      delete:
        - '--wait'
        - '--timeout=30s'
profiles:
  - name: dev
    activation:
      - command: dev
  - name: base
    build:
      artifacts:
        - image: golang-base
          docker:
            dockerfile: build/base.Dockerfile
            cacheFrom:
              - registry.access.redhat.com/ubi8/ubi:latest
