apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}'
  cluster: {}
  artifacts:
    - image: redhat-marketplace-operator
      custom:
        buildCommand: ./scripts/skaffold_build.sh
        dependencies:
          paths:
            - ./cmd
            - ./pkg
          ignore:
            - vendor/**
    - image: redhat-marketplace-reporter
      custom:
        buildCommand: ./scripts/skaffold-build-reporter.sh
        dependencies:
          paths:
            - ./cmd
            - ./pkg
          ignore:
            - vendor/**
deploy:
  helm:
    releases:
      - name: rhm-operator
        artifactOverrides:
          image: redhat-marketplace-operator
        chartPath: deploy/chart
        wait: true
        valuesFiles:
          - deploy/chart/values.yaml
  kubectl:
    manifests:
      - deploy/crds/*cr.yaml
    flags:
      disableValidation: true
      delete:
        - "--wait"
        - "--timeout=30s"
