apiVersion: batch/v1
kind: Job
metadata:
  name: rhm-meter-report
  labels:
    marketplace.redhat.com/report: 'true'
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 5
  template:
    spec:
      serviceAccount: redhat-marketplace-operator
      restartPolicy: Never
      containers:
        - name: reporter
          image: redhat-markplace-reporter
          imagePullPolicy: Always
          # additional args are added in factory
          args:
            [
              'report',
              '--cafile',
              '/etc/configmaps/operator-cert-ca-bundle/service-ca.crt',
              '--tokenfile',
              '/var/run/secrets/kubernetes.io/serviceaccount/token',
            ]
          volumeMounts:
            - mountPath: /etc/configmaps/operator-cert-ca-bundle
              name: operator-certs-ca-bundle
              readOnly: true
      volumes:
        - configMap:
            name: operator-certs-ca-bundle
          name: operator-certs-ca-bundle
