apiVersion: marketplace.redhat.com/v1alpha1
kind: MeterDefinition
metadata:
  name: example-meterdefinition-2
spec:
  # Add fields here
  group: partner.metering.com
  kind: App

  workloadVertexType: OperatorGroup
  workloads:
    - name: app-pods
      type: Pod
      ownerCRD:
        apiVersion: partner.metering.com/v1alpha1
        kind: App
      metricLabels:
        - label: container_spec_cpu_shares
          query: |-
            {job: kubelet}
          aggregation: sum
    - name: servicemon
      type: ServiceMonitor
      ownerCRD:
        apiVersion: partner.metering.com/v1alpha1
        kind: App
      metricLabels:
        - label: container_spec_cpu_shares
          query: |-
            {job: kubelet}
          aggregation: sum
  serviceMeters:
    - labels
  podMeters:
    - kube_pod_container_resource_requests
