apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: rhm-metric-state
  name: rhm-custom-metrics
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 2m
    port: custom-metrics 
    scrapeTimeout: 2m
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: server-name-replaced-at-runtime
  jobLabel: k8s-app
  selector:
    matchLabels:
        redhat.marketplace.com/name: redhat-marketplace-operator