kind: Service
apiVersion: v1
metadata:
  name: redhat-marketplace-operator
  namespace: openshift-redhat-marketplace
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
spec:
  selector:
    redhat.marketplace.com/name: redhat-marketplace-operator
  ports:
    - name: http-metrics
      port: 8383
    - name: cr-metrics
      port: 8686
    - name: custom-metrics
      port: 2112 