apiVersion: marketplace.redhat.com/v1alpha1
kind: MeterDefinition
metadata:
  name: example-meterdefinition
spec:
  # Add fields here
  group: partner.metering.com
  version: v1alpha1
  kind: App
  serviceMeters:
    - labels
  podMeters:
    - kube_pod_container_resource_requests
