apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  namespace: openshift-redhat-marketplace
  labels:
    operated-prometheus: 'true'
spec:
  selector:
    matchLabels:
      app: prometheus
  endpoints:
  - port: web

