apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-watch-keeper
