apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-reporter
rules:
- apiGroups:
  - ""
  resourceNames:
  - pull-secret
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
