apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    productID: 068a62892a1e4db39641342e592daa25
    productMetric: FREE
    productName: IBM Cloud Platform Common Services
  creationTimestamp: null
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-remoteresources3deployment-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redhat-marketplace-remoteresources3deployment
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-remoteresources3deployment
  namespace: openshift-redhat-marketplace
