apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-prometheus-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - watch
  - list
