apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-controller-manager-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    control-plane: controller-manager
    redhat.marketplace.com/name: redhat-marketplace-operator
status:
  loadBalancer: {}
