apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-watch-keeper-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redhat-marketplace-watch-keeper
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-watch-keeper
  namespace: openshift-redhat-marketplace
