apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    productID: 068a62892a1e4db39641342e592daa25
    productMetric: FREE
    productName: IBM Cloud Platform Common Services
  creationTimestamp: null
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-prometheus-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - watch
  - list
