apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: OLM
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-prometheus-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redhat-marketplace-prometheus
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-prometheus
  namespace: openshift-redhat-marketplace
