apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: redhat-marketplace-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MeterDefinition defines the meter workloads used to enable pay for use billing.
      displayName: Meter Definition
      kind: MeterDefinition
      name: meterdefinitions.marketplace.redhat.com
      version: v1beta1
    - description: MarketplaceConfig is configuration manager for our Red Hat Marketplace controllers
      displayName: Marketplace Config
      kind: MarketplaceConfig
      name: marketplaceconfigs.marketplace.redhat.com
      version: v1alpha1
    - description: MeterBase is the resource that sets up Metering for Red Hat Marketplace. This is an internal resource not meant to be modified directly.
      displayName: Meter Base
      kind: MeterBase
      name: meterbases.marketplace.redhat.com
      version: v1alpha1
    - description: RazeeDeployment is the resources that deploys Razee for the Red Hat Marketplace. This is an internal resource not meant to be modified directly.
      displayName: Razee Deployment
      kind: RazeeDeployment
      name: razeedeployments.marketplace.redhat.com
      version: v1alpha1
    - description: RemoteResourceS3 is the Schema for the remoteresources3s API
      displayName: Remote Resource S3
      kind: RemoteResourceS3
      name: remoteresources3s.marketplace.redhat.com
      version: v1alpha1
    - description: MeterDefinition defines the meter workloads used to enable pay for use billing.
      displayName: Meter Definition
      kind: MeterDefinition
      name: meterdefinitions.marketplace.redhat.com
      version: v1alpha1
  description: The Red Hat Marketplace Operator.
  displayName: Red Hat Marketplace Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - marketplace
  - multicloud
  links:
  - name: Redhat Marketplace Operator
    url: https://redhat-marketplace-operator.domain
  maturity: alpha
  provider:
    name: IBM
    url: https://marketplace.redhat.com
  version: 0.0.0
