---
# Source: redhat-marketplace-operator-template-chart/templates/operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redhat-marketplace-operator
  namespace: openshift-redhat-marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      redhat.marketplace.com/name: redhat-marketplace-operator
  template:
    metadata:
      labels:
        redhat.marketplace.com/name: redhat-marketplace-operator
    spec:
      serviceAccountName: redhat-marketplace-operator
      securityContext:
        null
      containers:
        - name: redhat-marketplace-operator
          # Replace this with the built image name
          image: quay.io/namsimar/redhat-marketplace-operator:1.0.0
          ports:
            - name: http-metrics
              containerPort: 8383
            - name: cr-metrics
              containerPort: 8686
            - name: custom-metrics
              containerPort: 2112
          imagePullPolicy: Always
          securityContext:
            {}
          command:
            - redhat-marketplace-operator
          env:
            - name: OPERATOR_NAME
              value: redhat-marketplace-operator
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_REPORTER
              value: quay.io/namsimar/redhat-marketplace-reporter:1.0.0
            - name: RELATED_IMAGE_KUBE_RBAC_PROXY
              value: quay.io/coreos/kube-rbac-proxy:v0.5.0
            - name: RELATED_IMAGE_METRIC_STATE
              value: quay.io/namsimar/redhat-marketplace-metric-state:1.0.0
            - name: RELATED_IMAGE_RHM_RRS3_DEPLOYMENT
              value: quay.io/razee/remoteresources3:0.6.2
            - name: RELATED_IMAGE_RHM_WATCH_KEEPER_DEPLOYMENT
              value: quay.io/razee/watch-keeper:0.5.3
