---
# Source: redhat-marketplace-operator-template-chart/templates/operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redhat-marketplace-operator
  namespace: openshift-redhat-marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      redhat.marketplace.com/name: redhat-marketplace-operator
  template:
    metadata:
      labels:
        redhat.marketplace.com/name: redhat-marketplace-operator
    spec:
      serviceAccountName: redhat-marketplace-operator
      securityContext:
        null
      containers:
        - name: redhat-marketplace-operator
          # Replace this with the built image name
          image: quay.io/mxpaspa/redhat-marketplace-operator:0.1.4
          imagePullPolicy: Always
          securityContext:
            {}
          command:
            - redhat-marketplace-operator
          args:
            - "--features=\"razee\""
          env:
            - name: OPERATOR_NAME
              value: redhat-marketplace-operator
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_RHM_RRS3_DEPLOYMENT
              value: quay.io/razee/remoteresources3:0.6.2
            - name: RELATED_IMAGE_RHM_WATCH_KEEPER_DEPLOYMENT
              value: quay.io/razee/watch-keeper:0.5.8
