apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: rhm-prometheus-meterbase-tls
  labels:
    prometheus: redhat-marketplace
  name: rhm-prometheus-meterbase
  namespace: openshift-redhat-marketplace
spec:
  ports:
  - name: web
    port: 9091
    targetPort: web
  - name: tenancy
    port: 9092
    targetPort: tenancy
  selector:
    app: prometheus
    prometheus: redhat-marketplace
  sessionAffinity: ClientIP
  type: ClusterIP
