apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  selector:
    matchLabels:
      redhat.marketplace.com/name: redhat-marketplace-operator
  replicas: 1
  template:
    metadata:
      labels:
        redhat.marketplace.com/name: redhat-marketplace-operator
    spec:
      containers:
        - name: manager
          args:
            - --enable-leader-election
          image: controller:latest
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          env:
            - name: OPERATOR_NAME
              value:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      terminationGracePeriodSeconds: 10
