---
# Source: helm-wrapper/templates/manager.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  selector:
    matchLabels:
      redhat.marketplace.com/name: redhat-marketplace-operator
  replicas: 1
  template:
    metadata:
      labels:
        redhat.marketplace.com/name: redhat-marketplace-operator
    spec:
      containers:
        - name: manager
          args:
            - --enable-leader-election
          image: quay.io/zach_source/redhat-marketplace-operator:1.0.7-alpha@sha256:32c10fa2f98d62c6515113d4639613f4143ab1ad20cabcbe785c51c78bf53f76
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: OPERATOR_NAME
              value: redhat-marketplace-operator
            - name: RELATED_IMAGE_REPORTER
              value: quay.io/zach_source/redhat-marketplace-reporter:1.0.7-alpha@sha256:3d10036914f7d5b8d6bae55a199028b7e90315c2796f63220905b89b7a15fd9f
            - name: RELATED_IMAGE_METRIC_STATE
              value: quay.io/zach_source/redhat-marketplace-metric-state:1.0.7-alpha@sha256:fe66c7340d6221e020be600e1babd833b6ffaee510a52412ae83372131390d98
            - name: RELATED_IMAGE_AUTHCHECK
              value: quay.io/zach_source/redhat-marketplace-authcheck:1.0.7-alpha@sha256:f2d3c24ba9d1e7bf1ca43329ba675a37e23bb571bbf65c8ba57209075d02b303
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      terminationGracePeriodSeconds: 10
      serviceAccountName: operator
