apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    marketplace.redhat.com/metering: 'true'
  name: rhm-operator-metrics
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 2m
    port: rhm-metrics
    scheme: http
    scrapeTimeout: 2m
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: server-name-replaced-at-runtime
  jobLabel: k8s-app
  selector:
    matchLabels:
      name: redhat-marketplace-operator