name: Bump Version

on:
  push:
    branches:
      - 'develop'
      - 'hotfix/**'

jobs:
  version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Tag version
        run: |
          VERSION=$(make current-version)
          RESULT=$(git tag --list | grep -E "$VERSION")

          if [ "$RESULT" != "" ] ; then
            VERSION=$(make bump-version)
            echo "bumping version to $VERSION"
            git add version/version.go
            git commit -m "chore: bumping version to $VERSION"
            git push
          else
            echo "tag $VERSION already exists" ;
          fi
