name: Create Manifest

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'
    paths-ignore:
      - 'deploy/olm-catalog/redhat-marketplace-operator/**'

env:
  pushImage: true

jobs:
  create-bundle:
    name: Create Manifest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: ['stable']
        include:
          - channel: 'stable'
            tags: ['release']
            draft: 'false'
            message: 'Stable release should be merged.'
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.pullRequestSecret }}

      - name: Get Vars
        id: vars
        run: |
          echo ::set-env name=pr_branch::$(echo $BRANCH | sed 's/refs\/heads\///')
          echo "::set-output name=version::$(make current-version)"
          echo "::set-output name=tag::sha-$(git rev-parse --short HEAD)"
          echo "::set-output name=hash::$(make current-version)-${FILEHASH:0:6}"
          echo "::set-env name=OPERATOR_IMAGE::quay.io/rh-marketplace/redhat-marketplace-operator:$(make current-version)-${FILEHASH:0:6}"
        env:
          FILEHASH: ${{ hashFiles('cmd/**', 'pkg/**', 'interal/**', 'version/**', 'go.sum', 'go.mod') }}
          BRANCH: ${{ github.ref }}

      - name: Install operator-sdk
        run: |
          make install-tools
          cd /tmp
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          python -m pip install --upgrade pip
          pip3 install -Iv operator-courier==$COURIER_VERSION
          curl -LO https://github.com/operator-framework/operator-registry/releases/download/${OPM_VERSION}/linux-amd64-opm
          chmod +x linux-amd64-opm && sudo cp linux-amd64-opm /usr/local/bin/opm && rm linux-amd64-opm
          echo "::add-path::/usr/local/bin"
          sudo apt-get install -y sed
          sudo snap install yq
        env:
          RELEASE_VERSION: v0.18.0
          OPM_VERSION: v1.12.5
          COURIER_VERSION: 2.1.7

      - name: Create CSV
        id: bundle
        run: make generate-csv bundle
        env:
          CSV_CHANNEL: ${{ matrix.channel }}
          IMAGE_REGISTRY: quay.io/rh-marketplace
          OPERATOR_IMAGE_TAG: ${{ steps.vars.outputs.hash }}
          CSV_DEFAULT_CHANNEL: ${{ matrix.channel == 'stable' }}

      - name: Create commit
        run: |
          git config user.name 'RHM Oper Bot'
          git config user.email 'rhmoper@us.ibm.com'
          git add ./deploy/olm-catalog
          git commit -m "chore: update csv"
          git push
