name: Release

on:
  # To create pull requests.
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-latest
    steps:
    - uses: Logerfo/gitflow-action@0.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # The `GITHUB_TOKEN` secret.
        auto-merge: false
        dev: develop

  tag:
    name: Tag
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Tag version
        run: |
          git tag $(make current-version)
          git push --5ags
