name: Release

on:
  # To create pull requests.
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-latest
    steps:
    - uses: Logerfo/gitflow-action@0.0.4
      with:
        github-token: ${{ secrets.pullRequestSecret }} # The `GITHUB_TOKEN` secret.
        auto-merge: false
        dev: develop

  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Tag version
        continue-on-error: true
        shell: bash {0}
        run: |
          VERSION=$(make current-version)
          RESULT=$(git tag --list | grep -E "$VERSION")
          if [ "$RESULT" = "" ] ; then
            echo "making tag $VERSION"
            git tag $VERSION
            git push --tags
          else
            echo "tag $VERSION already exists" ;
          fi
