name: Test Image

on:
  push:
    branches:
      - "master"
      - "release/**"
      - "hotfix/**"
      - "develop"
      - "feature/**"
      - "bugfix/**"
env:
  pushImage: true

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Get if gittag is pushed
        shell: bash {0}
        id: tag
        run: |
          VERSION=$(make current-version)
          RESULT=$(git tag --list | grep -E "$VERSION")
          IS_TAGGED=false
          if [ "$RESULT" != "" ] ; then
            IS_TAGGED=true
          fi

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Login Docker
        run: make docker-login
        env:
          DOCKER_USER: ${{ secrets["REDHAT_IO_USER"] }}
          DOCKER_PASSWORD: ${{ secrets["REDHAT_IO_PASSWORD"] }}
          REGISTRY: registry.redhat.io

      - name: Install tools
        run: |
          echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts
          make install-tools testbin

      - name: Test Unit
        run: |
          make test-ci-unit

      - uses: engineerd/setup-kind@v0.3.0

      - name: Test Integration
        env:
          USE_EXISTING_CLUSTER: true
          KUBEBUILDER_ATTACH_CONTROL_PLANE_OUTPUT: true
        run: |
          make load-kind test-ci-int

      - name: Cover
        run: |
          make test-cover-text
