apiVersion: marketplace.redhat.com/v1alpha1
kind: MeterDefinition
metadata:
  name: example-meterdefinition-2
spec:
  # Add fields here
  meterGroup: partner.metering.com
  meterKind: App
  workloadVertexType: OperatorGroup
  workloads:
    - name: app-pods
      type: Pod
      ownerCRD:
        apiVersion: partner.metering.com/v1alpha1
        kind: App
      metricLabels:
        - label: container_spec_cpu_shares
          aggregation: sum
